/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  BtnType,
  Color,
  Size,
} from './interface';

export namespace Components {
  interface MiButton {
    /**
    * 按钮颜色，可选值见 colors
    */
    'color': Color;
    /**
    * 是否禁用按钮
    */
    'disabled': boolean;
    /**
    * 将按钮宽度调整为其父宽度
    */
    'full': boolean;
    /**
    * 点击跳转的地址，指定此属性 button 的行为和 a 链接一致
    */
    'href': string;
    /**
    * 设置 button 原生的 type 值，可选值请参考 HTML 标准
    */
    'htmlType': string;
    /**
    * 设置按钮载入状态
    */
    'loading': boolean;
    /**
    * 其他属性,如aria-无障碍属性等
    */
    'props': {[prop: string]: any};
    /**
    * 设置按钮形状
    */
    'shape': 'circle' | 'round';
    /**
    * 设置按钮大小，可选值为 small large 或者不设
    */
    'size': Size;
    /**
    * a 链接的 target 属性，href 存在时生效
    */
    'target': string;
    /**
    * 按钮类型
    */
    'variant': BtnType;
  }
}

declare global {


  interface HTMLMiButtonElement extends Components.MiButton, HTMLStencilElement {}
  var HTMLMiButtonElement: {
    prototype: HTMLMiButtonElement;
    new (): HTMLMiButtonElement;
  };
  interface HTMLElementTagNameMap {
    'mi-button': HTMLMiButtonElement;
  }
}

declare namespace LocalJSX {
  interface MiButton extends JSXBase.HTMLAttributes<HTMLMiButtonElement> {
    /**
    * 按钮颜色，可选值见 colors
    */
    'color'?: Color;
    /**
    * 是否禁用按钮
    */
    'disabled'?: boolean;
    /**
    * 将按钮宽度调整为其父宽度
    */
    'full'?: boolean;
    /**
    * 点击跳转的地址，指定此属性 button 的行为和 a 链接一致
    */
    'href'?: string;
    /**
    * 设置 button 原生的 type 值，可选值请参考 HTML 标准
    */
    'htmlType'?: string;
    /**
    * 设置按钮载入状态
    */
    'loading'?: boolean;
    /**
    * 其他属性,如aria-无障碍属性等
    */
    'props'?: {[prop: string]: any};
    /**
    * 设置按钮形状
    */
    'shape'?: 'circle' | 'round';
    /**
    * 设置按钮大小，可选值为 small large 或者不设
    */
    'size'?: Size;
    /**
    * a 链接的 target 属性，href 存在时生效
    */
    'target'?: string;
    /**
    * 按钮类型
    */
    'variant'?: BtnType;
  }

  interface IntrinsicElements {
    'mi-button': MiButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


